USE AdventureWorks2019;
GO
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'FACT_SALES')
	DROP TABLE kociecki.FACT_SALES;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'DIM_CUSTOMER')
	DROP TABLE kociecki.DIM_CUSTOMER;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'DIM_TIME')
	DROP TABLE kociecki.DIM_TIME;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'DIM_PRODUCT')
	DROP TABLE kociecki.DIM_PRODUCT;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'DIM_SALESPERSON')
	DROP TABLE kociecki.DIM_SALESPERSON;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'MONTHS_NAMES')
	DROP TABLE kociecki.MONTHS_NAMES;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Kociecki' AND TABLE_NAME = 'WEEKDAY_NAMES')
	DROP TABLE kociecki.WEEKDAY_NAMES;